# Generated by Django 4.2.4 on 2024-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grName', models.CharField(max_length=200)),
                ('grDescriptionn', models.TextField(blank=True, null=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
