# Generated by Django 4.2.4 on 2024-02-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_cluster_group_admin_messages_group_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='topic',
            new_name='cluster',
        ),
    ]
