# Generated by Django 4.2.4 on 2024-02-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_rename_topic_group_cluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='grDescriptionn',
            new_name='GroupDescriptionn',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='grName',
            new_name='GroupName',
        ),
    ]
